const assert=require('node:assert/strict'),C=require('../src/core.js');
const results=[];
function check(name,test){test();results.push({name,status:'pass'});}
check('Feeding spends food without generating green points',()=>{const s=C.fresh();for(let i=0;i<3;i++)assert.equal(C.feed(s),true);assert.equal(C.feed(s),false);assert.equal(s.food,0);assert.equal(s.feeds,3);assert.equal(C.points(s),80);assert.equal(C.level(s),2);});
check('Weekly points and trial food cannot be claimed twice',()=>{const s=C.fresh();assert.equal(C.collect(s),true);assert.equal(C.collect(s),false);assert.equal(C.points(s),100);assert.equal(C.claimFood(s),true);assert.equal(C.claimFood(s),false);assert.equal(s.food,5);});
check('Puzzle can be solved through real swaps',()=>{const s=C.fresh();assert.equal(C.swap(s,0,1),false);assert.equal(C.swap(s,4,5),false);assert.equal(C.swap(s,6,8),true);assert.equal(s.moves,3);assert.deepEqual(s.tiles,[0,1,2,3,4,5,6,7,8]);});
check('Pipe routing rejects broken routes and accepts a connected inlet/outlet',()=>{const s=C.fresh();assert.equal(C.trace(s).ok,false);s.rot=[1,1,2,1,3,0,2,0,0];assert.equal(C.trace(s).ok,true);assert.deepEqual(C.trace(s).seen,[3,4,1,2,5,8]);s.rot[8]=1;assert.equal(C.trace(s).ok,false);});
check('Replaying both games never duplicates rewards',()=>{const s=C.fresh();for(let i=0;i<10;i++){C.award(s,'photo');C.award(s,'water');}assert.equal(s.food,7);assert.equal(C.points(s),80);assert.equal(s.photoWon,true);assert.equal(s.waterWon,true);});
check('Previous v3 state retains progress and converts legacy outfit',()=>{const s=C.sanitize({food:9,feeds:14,collected:true,photoWon:true,fishType:'gold',fishWear:'bow',keeper:'秦天',partners:'秦天,小李,小李,小王',tiles:[0,1,2,3,4,5,6,7,8]});assert.equal(s.food,9);assert.equal(s.feeds,14);assert.equal(s.fishWear,'sailor');assert.equal(s.partners,'小李、小王');assert.equal(C.points(s),100);});
check('Damaged storage and out-of-range values are handled safely',()=>{const s=C.sanitize({food:-10,feeds:Infinity,tiles:[0,0,0,0,0,0,0,0,0],rot:[9],fishType:'other',partners:'A,B,C,D,E,F,G'});assert.equal(s.food,3);assert.equal(s.feeds,0);assert.equal(new Set(s.tiles).size,9);assert.equal(s.rot.length,9);assert.equal(s.fishType,'clown');assert.equal(s.partners.split('、').length,5);});
check('Soft reset preserves personalization and full reset clears it',()=>{const s=C.sanitize({name:'泡泡',keeper:'Alex',partners:'Jo',fishType:'blue',fishWear:'scarf',lang:'en',food:0,feeds:18,photoWon:true});const soft=C.reset(s,false);assert.equal(soft.name,'泡泡');assert.equal(soft.fishType,'blue');assert.equal(soft.fishWear,'scarf');assert.equal(soft.food,3);assert.equal(soft.photoWon,false);const full=C.reset(s,true);assert.equal(full.name,'小满');assert.equal(full.partners,'');assert.equal(full.lang,'en');assert.equal(full.food,3);});
console.log(JSON.stringify({passed:results.length,results},null,2));
