(() => {
  'use strict';
  const $=id=>document.getElementById(id), C=PondCore, A=JSON.parse($('assets').textContent);
  const STORAGE='campus-water-forest:pond-v5', reduced=matchMedia('(prefers-reduced-motion: reduce)');
  let s=C.fresh(), storageAvailable=true;
  try {
    const current=localStorage.getItem(STORAGE);
    if(current) s=C.sanitize(JSON.parse(current));
    else {
      const oldKey='codex:visualization-widget-state-v2:'+JSON.stringify([location.pathname,location.search]);
      const old=JSON.parse(localStorage.getItem(oldKey)||'null');
      const raw=old?.privateContent?.state||old?.widgetState?.privateContent?.state;
      if(raw){s=C.sanitize(raw);s.started=true;}
    }
  } catch {storageAvailable=false;}
  const icons={
    food:'<circle cx="7" cy="7" r="2"/><circle cx="16" cy="5" r="1.6"/><circle cx="14" cy="14" r="2.3"/><circle cx="5" cy="17" r="1.4"/><circle cx="20" cy="18" r="1.4"/>',
    tree:'<path d="M12 3 6 10h3l-5 6h6v5h4v-5h6l-5-6h3z"/>',
    shirt:'<path d="m8 4-5 3 3 5 2-1v10h8V11l2 1 3-5-5-3c-1 4-7 4-8 0Z"/>',
    group:'<circle cx="8" cy="7" r="3"/><circle cx="17" cy="8" r="2.5"/><path d="M2 21v-4a6 6 0 0 1 12 0v4M15 13a5 5 0 0 1 7 4v4"/>',
    chevron:'<path d="m9 5 7 7-7 7"/>',
    tank:'<rect x="2" y="5" width="20" height="15" rx="4"/><path d="M2 9h20m-9 5c-3-3-7-1-7 1s4 4 7 1l3 2v-5zM6 5V3m12 2V3"/>',
    game:'<path d="M7 7h10a4 4 0 0 1 4 3l1 8a2 2 0 0 1-3 2l-4-3H9l-4 3a2 2 0 0 1-3-2l1-8a4 4 0 0 1 4-3Z"/><path d="M6 10v6m-3-3h6m6-2h.1m3 3h.1"/>',
    bag:'<rect x="4" y="7" width="16" height="14" rx="4"/><path d="M8 8V6a4 4 0 0 1 8 0v2m-8 5h8m-4-2v4"/>',
    user:'<circle cx="12" cy="6" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2Z"/>',
    play:'<path d="m7 3 14 9-14 9z"/>',
    sound:'<path d="M10 5 5 9H2v6h3l5 4Zm5 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',
    mute:'<path d="M10 5 5 9H2v6h3l5 4Zm5 4 6 6m0-6-6 6"/>',
    water:'<path d="M12 2C10 6 4 11 4 16a8 8 0 0 0 16 0c0-5-6-10-8-14Z"/><path d="M8 15a4 4 0 0 0 4 5"/>',
    leaf:'<path d="M20 3C2 1 0 16 9 19S23 13 20 3ZM4 21 16 8"/>',
    reset:'<path d="M3 9a9 9 0 1 1 0 7m0-14v7h7"/>',
    book:'<path d="M12 5C9 2 3 3 2 4v16c4-2 8-1 10 1 2-2 6-3 10-1V4c-4-2-8-1-10 1Zm0 0v16"/>',
    photo:'<rect x="2" y="4" width="20" height="16" rx="3"/><circle cx="8" cy="9" r="2"/><path d="m2 17 6-5 5 5 4-4 5 4"/>',
    check:'<path d="m5 12 4 4L20 5"/>',
    language:'<path d="M2 5h11M7 2v3m-3 0c1 5 4 8 8 11m-1-11c-1 5-4 9-9 12m11 4 4-11 4 11m-7-3h6"/>',
    badge:'<path d="m8 13-2 9 6-3 6 3-2-9"/><circle cx="12" cy="8" r="6"/><path d="m12 5 .7 2.1H15l-1.8 1.3.7 2.2L12 9.3l-1.9 1.3.7-2.2L9 7.1h2.3Z"/>'
  };
  const icon=n=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">'+(icons[n]||icons.water)+'</svg>';
  // Chinese strings are optional interface translations; comments and documentation use English.
  const L=(zh,en)=>s.lang==='en'?en:zh;
  const dictionary={careControls:['照顾小鱼','Care controls'],exploreControls:['探索与任务','Explore & tasks'],brand:['滴水成林','Campus Reef'],campusPond:['校园小鱼塘','Campus Pond'],greenPoints:['绿色积分','Green points'],food:['鱼粮','Fish food'],feed:['喂食','Feed'],dress:['装扮','Dress'],together:['共养','Together'],collect:['领积分','COLLECT'],aquarium:['鱼塘','Aquarium'],challenges:['挑战','Challenges'],inventory:['物品','Inventory'],guardian:['守护','Guardian'],you:['我的','You'],localDemo:['校园节水 · 最终演示','Campus water project · Final demo'],welcomeCopy:['照顾一条小鱼，守护一片校园。','Care for a little fish. Look after your campus.'],play:['开始','Play'],welcomeFoot:['课堂原型 · v6\n进度保存在此浏览器，用水记录为示例。','Class prototype · v6\nSaved in this browser. Water records are examples.']};
  const text=k=>(dictionary[k]||[k,k])[s.lang==='en'?1:0];
  const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fishLabel=type=>PondLife.label(type,L);
  const owners=()=>[s.keeper,...s.partners.split('、').filter(Boolean)];
  const petAsset=(type=s.fishType,wear=s.fishWear)=>PondLife.asset(A,type,wear);
  let panel=null,sub='fish',selectedTile=null,wet=[],returnFocus=null,feeding=false,reacting=false,plaqueOpen=false;
  let toastTimer,fishTimer,feedTimer,floatTimer,audioContext,confettiFrame=0,gameMessage='',lastSpeech=null,lastToast=null;
  const tones=new Set();
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(s));storageAvailable=true;}catch{storageAvailable=false;}}
  function hydrate(container=document){container.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));container.querySelectorAll('[data-t]').forEach(el=>el.textContent=text(el.dataset.t));}
  function toast(zh,en){lastToast=[zh,en];clearTimeout(toastTimer);$('toast').textContent=L(zh,en);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3000);}
  function speech(zh,en){lastSpeech=[zh,en];clearTimeout(fishTimer);$('fish-speech').textContent=L(zh,en);$('fish-speech').hidden=false;fishTimer=setTimeout(()=>{$('fish-speech').hidden=true;reacting=false;paintFish();},2100);}
  function paintFish(){
    const el=$('pet-image');
    el.src=s.fishType==='clown'&&s.fishWear==='none'&&(feeding||reacting)?A[feeding?'fishEat':'fishReact']:petAsset();
    el.alt=fishLabel(s.fishType);
    const scale=C.growthScale(s), base=({small:125,normal:170,large:230})[s.fishSize];
    const pixels=Math.min(base*scale,innerWidth*.65);
    $('pet').style.width=pixels+'px';$('pet').style.height=pixels*.765+'px';
    $('pet').setAttribute('aria-label',L('和'+s.name+'打招呼','Say hello to '+s.name));
    $('welcome-fish').src=petAsset();PondLife.render(s,A,L);
  }
  function goal(){
    if(!s.petChosen)return{title:L('下一步：选择一条小鱼','Next up: Choose your fish'),progress:0,reward:L('6 种伙伴','6 fish'),action:'wardrobe'};
    if(s.feeds===0)return{title:L('下一步：喂小鱼一次 · 0/1','Next up: Feed your fish · 0/1'),progress:20,reward:'+20 XP',action:'feed'};
    if(!s.photoWon&&!s.waterWon)return{title:L('下一步：完成一个校园挑战','Next up: Complete a campus challenge'),progress:40,reward:L('+2 鱼粮','+2 food'),action:'games'};
    if(!s.collected)return{title:L('下一步：查看示例用水记录','Next up: Review sample water records'),progress:60,reward:'+20 ✦',action:'records'};
    if(!s.certificate)return{title:L('下一步：点开校园守护牌','Next up: Open your guardian plaque'),progress:80,reward:L('守护预览','Preview'),action:'campus'};
    if(!s.photoWon||!s.waterWon)return{title:L('下一步：集齐两枚挑战徽章','Next up: Collect both challenge badges'),progress:90,reward:L('+2 鱼粮','+2 food'),action:'games'};
    if(!s.babyType)return{title:L('下一步：到 Lv. 3 迎接幼鱼','Next up: Welcome a baby at Lv. 3'),progress:Math.min(100,Math.round(s.feeds/8*100)),reward:'Lv. '+C.level(s)+'/3',action:'nursery'};
    return{title:L('初次旅程完成 · 继续陪伴小鱼','First journey complete · Keep caring'),progress:100,reward:L('2/2 徽章','2/2 badges'),action:'bag'};
  }
  function render(){
    document.documentElement.lang=s.lang==='en'?'en':'zh-CN';document.title=text('brand')+' · '+text('campusPond');hydrate();
    $('points').textContent=C.points(s);$('food').textContent=s.food;$('level').textContent='Lv. '+C.level(s);$('profile-level').textContent='Lv. '+C.level(s);
    $('feed-sub').textContent=L(s.food+' 份鱼粮',s.food+' food');$('friend-sub').textContent=L(owners().length+' 位守护者',owners().length+' guardian'+(owners().length>1?'s':''));
    $('collect-sub').textContent=s.collected?L('示例奖励已领取','Sample reward claimed'):L('+20 · 示例奖励','+20 · sample reward');$('collect').disabled=s.collected;
    $('feed').disabled=feeding;$('fish-count').textContent=fishLabel(s.fishType);$('game-count').textContent=(Number(s.photoWon)+Number(s.waterWon))+'/2';$('bag-count').textContent=L(s.food+' 份鱼粮',s.food+' food');$('guardian-sub').textContent=C.points(s)+'/100';
    $('language').textContent=s.lang==='zh'?'EN':'ZH';$('language').setAttribute('aria-label',s.lang==='zh'?'Switch to English':'Switch to Chinese');$('sound').innerHTML=icon(s.muted?'mute':'sound');$('sound').setAttribute('aria-label',s.muted?L('开启音效','Turn sound on'):L('关闭音效','Turn sound off'));$('sound').setAttribute('aria-pressed',String(!s.muted));
    const g=goal();$('goal-title').textContent=g.title;$('goal-progress').style.width=g.progress+'%';$('goal-reward').textContent=g.reward;$('next-goal').dataset.next=g.action;
    $('welcome').hidden=s.started;$('interface').style.visibility=s.started?'visible':'hidden';$('interface').inert=!s.started||!!panel;$('fish-world').inert=!s.started||!!panel;$('welcome').inert=s.started;
    if(lastSpeech&&!$('fish-speech').hidden)$('fish-speech').textContent=L(...lastSpeech);if(lastToast&&!$('toast').hidden)$('toast').textContent=L(...lastToast);
    $('controls-toggle').setAttribute('aria-label',s.controlsPinned?L('自动收起工具栏','Auto-hide controls'):L('固定显示工具栏','Keep controls visible'));
    $('controls-toggle').setAttribute('aria-pressed',String(s.controlsPinned));
    $('controls-toggle').title=L('靠近上下边缘展开，也可以固定显示','Hover near the top or bottom, or pin the controls');
    PondControls.setPinned(s.controlsPinned);
    $('close-sheet').setAttribute('aria-label',L('关闭','Close'));document.querySelector('.dock').setAttribute('aria-label',L('游戏导航','Game navigation'));paintFish();
    document.querySelectorAll('[data-tab]').forEach(btn=>{const active=btn.dataset.tab===(panel==='games'||panel==='photo'||panel==='water'?'games':['campus','bag','profile'].includes(panel)?panel:'home');btn.classList.toggle('active',active);if(active)btn.setAttribute('aria-current','page');else btn.removeAttribute('aria-current');});
  }
  const button=(label,act,classes='')=>'<button class="btn '+classes+'" data-act="'+act+'">'+label+'</button>';
  const menuRow=(ico,label,act,right='')=>'<button class="menu-row" data-act="'+act+'">'+icon(ico)+'<span>'+label+'</span><small>'+right+'</small>'+icon('chevron')+'</button>';
  const note=html=>'<div class="note">'+html+'</div>';
  function titleFor(kind){const map={nursery:[L('小鱼一家','Fish family'),'leaf'],wardrobe:[L('我的小鱼','My fish'),'shirt'],friends:[L('一起共养','Care together'),'group'],food:[L('鱼粮补给','Fish food'),'food'],games:[L('校园挑战','Campus challenges'),'game'],photo:[L('校园照片拼图','Campus photo puzzle'),'photo'],water:[L('接通小水路','Connect the water'),'water'],records:[L('我的用水记录','My water records'),'water'],campus:[L('校园守护','Campus guardian'),'tree'],bag:[L('我的物品','Inventory'),'bag'],profile:[L('我的','You'),'user'],name:[L('给小鱼起名','Name your fish'),'user'],reset:[L('重新开始','Start again'),'reset'],help:[L('怎么玩','How to play'),'book'],about:[L('关于项目与素材','Project & credits'),'book'],reward:[L('奖励到啦','Reward unlocked'),'badge']};return map[kind]||map.profile;}
  function open(kind,tab){if(!panel)returnFocus=document.activeElement;panel=kind;if(tab)sub=tab;$('overlay').hidden=false;renderPanel();render();$('close-sheet').focus({preventScroll:true});}
  function close(){panel=null;$('overlay').hidden=true;stopFireworks();render();const target=returnFocus?.isConnected&&!returnFocus.disabled?returnFocus:document.querySelector('[data-tab="home"]');returnFocus=null;PondControls.revealFor(target);target.focus({preventScroll:true});}
  function renderPanel(){
    if(!panel)return;const [title,ico]=titleFor(panel);$('sheet-title').innerHTML=icon(ico)+esc(title);$('sheet').dataset.panel=panel;const body=$('sheet-body');let html='';
    if(panel==='wardrobe'){
      html='<div class="tabs">'+['fish','wear'].map(k=>'<button class="tab '+(sub===k?'active':'')+'" data-act="wardrobe-tab" data-value="'+k+'">'+icon(k==='fish'?'tank':'shirt')+L(k==='fish'?'选鱼':'大小与装扮',k==='fish'?'Fish':'Size & outfit')+'</button>').join('')+'</div>';
      if(sub==='wear'){
        html+='<div class="preview-fish"><img src="'+petAsset()+'" alt="'+fishLabel(s.fishType)+'"><span>'+esc(s.name)+' · '+fishLabel(s.fishType)+'</span></div><span class="section-label">'+L('体型','Size')+'</span><div class="size-options">'+['small','normal','large'].map((v,i)=>'<button data-act="size" data-value="'+v+'" aria-pressed="'+(s.fishSize===v)+'" class="'+(s.fishSize===v?'selected':'')+'">'+L(['小只','标准','大只'][i],['Small','Medium','Large'][i])+'</button>').join('')+'</div><span class="section-label">'+L('今日装扮','Today’s outfit')+'</span><div class="wear-cards">'+['none','sailor','scarf'].map((v,i)=>'<button data-act="wear" data-value="'+v+'" aria-pressed="'+(s.fishWear===v)+'" class="'+(s.fishWear===v?'selected':'')+'"><img src="'+petAsset(s.fishType,v)+'" alt="">'+L(['自然模样','海岸水手领','奶油针织围巾'][i],['Natural','Sailor collar','Knitted scarf'][i])+'</button>').join('')+'</div>'+note(L('换装立即保存。小鱼照片和衣服沿用我们的已有素材。','Your outfit is saved immediately. These are our existing photo-based fish assets.'));
      }else html+='<p class="care-hint">'+L('选择或确认一位伙伴，再回鱼塘照顾它。','Choose or confirm a companion, then return to the pond to care for it.')+'</p><div class="cards fish-catalog">'+C.species.map(v=>{
        const fish=PondLife.catalog[v];
        return '<article class="item-card '+(s.fishType===v?'selected':'')+'"><img src="'+petAsset(v,'none')+'" alt="'+fishLabel(v)+'"><h3>'+fishLabel(v)+'</h3><span class="tag mint">'+L(...fish.tag)+'</span><small>'+L(...fish.detail)+'</small><button class="btn" data-act="choose-fish" data-value="'+v+'" aria-pressed="'+(s.fishType===v)+'">'+(s.fishType===v?(s.petChosen?icon('check')+L('已选择','Selected'):L('就选它','Keep this fish')):L('选择','Choose'))+'</button></article>';
      }).join('')+'</div>'+note(L('六种伙伴均可选择。每次升级都会长大一点；Lv. 3 可迎接一条幼鱼。','Choose any of six fish. Each level makes your fish a little larger; welcome a baby at Lv. 3.'));
      html+='<div class="actions">'+button(L('回鱼塘','Back to pond'),'close','full')+'</div>';
    }
    if(panel==='friends')html='<p>'+L('一个人养，也可以约上伙伴一起养。','Keep a pond of your own, or add your friends.')+'</p><label class="section-label" for="keeper-input">'+L('我的名字','My name')+'</label><input class="input" id="keeper-input" maxlength="12" value="'+esc(s.keeper)+'"><label class="section-label" for="partners-input">'+L('共养伙伴（选填，最多 5 位）','Friends (optional, up to 5)')+'</label><input class="input" id="partners-input" maxlength="80" value="'+esc(s.partners)+'" placeholder="'+L('多个名字用逗号隔开','Separate names with commas')+'"><div class="roster">'+owners().map(x=>'<span>'+esc(x)+'</span>').join('')+'</div>'+button(L('保存共养设置','Save guardians'),'save-friends','full')+note(L('名字会显示在守护牌预览里。当前为本机展示，其他手机不会自动同步。','Names appear on your guardian plaque preview. This is a local demo; devices do not sync.'));
    if(panel==='friends')html+='<div class="companion-note"><span>'+L('4 条演示伙伴鱼在同一片水中游动，营造一起养鱼的感觉。','Four demo companions share the pond and bring it to life.')+'</span>'+button(s.companions?L('隐藏伙伴鱼','Hide companions'):L('显示伙伴鱼','Show companions'),'toggle-companions','secondary')+'</div>'+menuRow('leaf',L('小鱼一家','Fish family'),'open-nursery',s.babyType?L('1 条幼鱼','1 baby'):'Lv. '+C.level(s)+'/3')+note(L('这些伙伴鱼是本机演示角色。真实伙伴的名字可填写在上方，存档保存在自己的浏览器。','These companions are local demo characters. Add your own guardian names above; progress stays in your browser.'));
    if(panel==='nursery'){
      const ready=C.level(s)>=C.nurseryLevel, feedsLeft=Math.max(0,8-s.feeds);
      html='<div class="nursery-card"><div class="nursery-fish"><img src="'+petAsset(s.fishType,'none')+'" alt="'+fishLabel(s.fishType)+'">'+(s.babyType?'<img class="nursery-baby" src="'+petAsset(s.babyType,'none')+'" alt="'+L('幼鱼','Baby fish')+'">':'')+'</div><h3>'+L(s.babyType?'小鱼一家，一起长大':'给成长一个新的期待',s.babyType?'A little family in your pond':'A little family begins with care')+'</h3><p>'+L(s.babyType?'幼鱼会跟着你的小鱼游动。换鱼或装扮时，幼鱼保留出生时的鱼种。':'喂食获得成长值。达到 Lv. 3 后，可以迎接一条同鱼种的幼鱼。',s.babyType?'Your baby swims alongside your fish and keeps its own species when you change your companion.':'Feed your fish to earn XP. At Lv. 3, welcome one baby of the same species.')+'</p><div class="nursery-meta"><span>Lv. '+C.level(s)+'</span><span>'+L(ready?'已达到成长目标':'还需喂食 '+feedsLeft+' 次',ready?'Growth milestone reached':feedsLeft+' more '+(feedsLeft===1?'feed':'feeds')+' to Lv. 3')+'</span></div><div class="xp-track"><i style="width:'+Math.min(100,s.feeds/8*100)+'%"></i></div><div class="actions"><button class="btn full" data-act="welcome-baby" '+(!ready||s.babyType?'disabled':'')+'>'+L(s.babyType?'幼鱼已加入鱼塘':ready?'迎接一条幼鱼':'Lv. 3 解锁幼鱼',s.babyType?'Baby already welcomed':ready?'Welcome a baby fish':'Unlock a baby at Lv. 3')+'</button></div></div><div class="actions">'+button(L('获取鱼粮','Find fish food'),'open-food','secondary')+button(L('回鱼塘','Back to pond'),'close')+'</div>'+note(L('幼鱼是游戏中的成长奖励，每轮进度可迎接一次并保存在本机。绿色积分仍来自示例用水记录。','One baby can be welcomed per saved journey. This is a game growth reward; sample water records remain the source of green points.'));
    }
    if(panel==='food')html='<div class="stats"><div class="stat"><strong>'+s.food+'</strong><small>'+L('份鱼粮','portions of food')+'</small></div><div class="stat"><strong>'+s.feeds+'</strong><small>'+L('次陪伴喂食','feeds so far')+'</small></div></div><p>'+L('每次喂食消耗 1 份鱼粮，增加 20 成长值。','Each feed uses one portion of food and adds 20 XP.')+'</p><button class="btn full" data-act="gift" '+(s.gift?'disabled':'')+'>'+L(s.gift?'试玩补给已领取':'领取试玩补给 · +2 鱼粮',s.gift?'Trial supply already claimed':'Claim trial supply · +2 food')+'</button><div class="actions">'+button(L('去校园挑战','Play a campus challenge'),'open-games','secondary full')+'</div>'+note(L('补给与每关首次通关奖励各领取一次。游戏鱼粮和成长不兑换绿色积分。','The trial supply and each first-clear reward can be claimed once. Food and XP do not create green points.'));
    if(panel==='games')html='<p>'+L('带一点礼物，回去陪小鱼。','Bring a little reward back to your fish.')+'</p><article class="challenge-card"><img src="'+A.aerial+'" alt="'+L('团队拍摄的校园夜景','Our team’s campus night photograph')+'"><div><span class="reward-chip">'+L(s.photoWon?'✓ 已通关':'+2 鱼粮',s.photoWon?'✓ Completed':'+2 food')+'</span><h3>'+L('拼回我们的校园','Piece together our campus')+'</h3><p>'+L('对照原图，点击两块照片交换位置。','Use the reference photo. Tap two tiles to swap them.')+'</p>'+button(L(s.photoWon?'再玩一次':'开始拼图',s.photoWon?'Play again':'Start puzzle'),'open-photo')+'</div></article><article class="challenge-card"><div class="water-preview">'+icon('water')+'</div><div><span class="reward-chip">'+L(s.waterWon?'✓ 已通关':'+2 鱼粮',s.waterWon?'✓ Completed':'+2 food')+'</span><h3>'+L('接通小水路','Connect the water')+'</h3><p>'+L('转动管道，把水从左边送到右下方。','Rotate the pipes and lead water to the lower-right outlet.')+'</p>'+button(L(s.waterWon?'再试一次':'开始接水',s.waterWon?'Try again':'Connect pipes'),'open-water')+'</div></article>'+note(L('每关首次完成：2 份鱼粮 + 1 枚徽章。重复通关不重复发奖。','First clear of each challenge: 2 food + 1 badge. Repeat clears do not grant extra rewards.'));
    if(panel==='photo'){
      const correct=s.tiles.filter((v,i)=>v===i).length;
      html='<div class="tabs">'+['aerial','walkway'].map((v,i)=>'<button class="tab '+(s.photo===v?'active':'')+'" data-act="photo-source" data-value="'+v+'">'+L(['校园夜景','校园步道'][i],['Campus at night','Campus walkway'][i])+'</button>').join('')+'</div><div class="game-meta"><span>'+L('交换 '+s.moves+' 次',s.moves+' swaps')+'</span><span>'+correct+' / 9 '+L('块归位','in place')+'</span></div><div class="photo-layout"><div class="photo-board">'+s.tiles.map((piece,i)=>'<button class="photo-tile '+(selectedTile===i?'selected':'')+'" data-act="tile" data-index="'+i+'" aria-label="'+L('拼图第'+(i+1)+'格，原图第'+(piece+1)+'块','Tile '+(i+1)+', photo piece '+(piece+1))+'" aria-pressed="'+(selectedTile===i)+'" style="background-image:url('+A[s.photo]+');background-position:'+(piece%3)*50+'% '+Math.floor(piece/3)*50+'%"></button>').join('')+'</div><aside class="reference"><img src="'+A[s.photo]+'" alt="'+L('拼图原图','Puzzle reference')+'"><small>'+L('原图参考','Reference')+'</small></aside></div><p class="game-result" role="status">'+(gameMessage||L('先点一块，再点另一块交换。','Tap one tile, then another to swap.'))+'</p><div class="actions">'+button(L('重新打乱','Shuffle'),'shuffle','secondary')+button(L('返回挑战','Challenges'),'open-games')+'</div>'+note(L('照片来自团队实拍，原件为 phot/6.jpg 和 7.jpg。','Team photographs: phot/6.jpg and 7.jpg.'));
    }
    if(panel==='water')html='<p>'+L('入口在左侧中间，出口在右下方。点击一格旋转 90°。','The inlet is on the middle left; the outlet is at the lower right. Tap a pipe to rotate 90°.')+'</p><div class="pipe-wrap"><span class="inlet" aria-hidden="true">→</span><div class="pipe-board">'+s.rot.map((v,i)=>'<button class="pipe '+(wet.includes(i)?'wet':'')+'" data-act="pipe" data-index="'+i+'" aria-label="'+L('第'+(i+1)+'格，连接','Pipe '+(i+1)+', connected to ')+C.ports(s,i).map(p=>L(['上','右','下','左'][p],['top','right','bottom','left'][p])).join(L('和',' and '))+'">'+C.ports(s,i).map(p=>'<i class="'+['n','e','s','w'][p]+'"></i>').join('')+'<b></b><small>'+(i+1)+'</small></button>').join('')+'</div><div class="outlet" aria-hidden="true">↓</div></div><p class="game-result" role="status">'+(gameMessage||L('转好管道后，放水检查路线。','Rotate the pipes, then test the flow.'))+'</p><div class="actions">'+button(L('放水试试','Let it flow'),'flow')+button(L('路线提示','Hint'),'pipe-hint','secondary')+'</div><div class="actions">'+button(L('返回挑战','Challenges'),'open-games','secondary full')+'</div>';
    if(panel==='records'){
      const data=[10,9,8,7,8,7,7], fees=[1.20,1.10,.98,.85,.99,.87,.88],x=i=>42+i*62,y=v=>191-v*12;
      let chart='<svg class="chart" viewBox="0 0 460 245" role="img" aria-label="'+L('示例使用时长：10、9、8、7、8、7、7分钟，历史基线10分钟','Sample durations: 10, 9, 8, 7, 8, 7, 7 minutes; baseline 10 minutes')+'">';
      [0,4,8,12].forEach(n=>chart+='<path d="M42 '+y(n)+'H437" stroke="#87aeb622"/><text x="27" y="'+(y(n)+4)+'" fill="#89a7b2" font-size="11" text-anchor="end">'+n+'</text>');
      chart+='<text x="42" y="21" fill="#9db9c1" font-size="11">'+L('使用时长 / 分钟','Duration / minutes')+'</text><path d="M42 '+y(10)+'H437" stroke="#e6c18a" stroke-dasharray="5 5" opacity=".65"/>';
      const path=data.map((n,i)=>(i?'L':'M')+x(i)+' '+y(n)).join(' ');chart+='<path d="'+path+'L414 191H42Z" fill="#69cdb410"/><path d="'+path+'" fill="none" stroke="#72d6c0" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>';
      data.forEach((n,i)=>chart+='<circle cx="'+x(i)+'" cy="'+y(n)+'" r="4" fill="#88e0c8"/><text x="'+x(i)+'" y="'+(y(n)-13)+'" text-anchor="middle" fill="#cee9e8" font-size="12">'+n+'</text><text x="'+x(i)+'" y="217" text-anchor="middle" fill="#92aeb9" font-size="11">9/'+(14+i)+'</text>');chart+='</svg>';
      html='<span class="tag gold">'+L('示例数据 · 尚未接入趣智校园','Sample data · Not connected to Quzhi Campus')+'</span><p>'+L('计划关联趣智校园的使用时间、时长和费用记录。当前用下列示例体验完整流程。','We plan to use Quzhi Campus timestamps, duration and fees. These sample records demonstrate the flow.')+'</p><div class="stats"><div class="stat"><strong>8 <small>'+L('分钟 / 日','min / day')+'</small></strong><small>'+L('本周示例均值','Sample week average')+'</small></div><div class="stat"><strong>10 <small>'+L('分钟 / 日','min / day')+'</small></strong><small>'+L('示例历史基线','Sample baseline')+'</small></div><div class="stat"><strong>20</strong><small>'+L('示例绿色积分','Sample green points')+'</small></div></div>'+chart+'<button class="btn full '+(s.collected?'secondary':'')+'" data-act="collect" '+(s.collected?'disabled':'')+'>'+L(s.collected?'本周积分已领取':'领取 20 示例积分',s.collected?'This week’s points claimed':'Collect 20 points')+'</button><details class="details"><summary>'+L('查看 7 天示例明细','View the 7 sample records')+'</summary><table class="data-table"><thead><tr><th>'+L('日期','Date')+'</th><th>'+L('时长 / 分钟','Minutes')+'</th><th>'+L('费用 / 元','Fee / CNY')+'</th></tr></thead><tbody>'+data.map((n,i)=>'<tr><td>9/'+(14+i)+'</td><td>'+n+'</td><td>'+fees[i].toFixed(2)+'</td></tr>').join('')+'</tbody></table></details>'+note(L('这些时长、费用和积分均为演示。时长不能直接换算为节水升数，小游戏不产生绿色积分。','Durations, fees and points are examples. Time does not directly measure litres saved. Mini-games do not create green points.'));
    }
    if(panel==='campus'){
      html='<div class="tree-photo"><img src="'+A.treePlaque+'" alt="'+L('校园A01树木实拍，木牌为合成预览','Campus tree A01; the small plaque is a composite preview')+'"><button class="plaque-hotspot" data-act="plaque" aria-expanded="'+plaqueOpen+'" aria-label="'+L(plaqueOpen?'收起守护牌':'点开树上的守护牌',plaqueOpen?'Close guardian plaque':'Open the guardian plaque')+'">'+icon('user')+'</button><div class="plaque-overlay" '+(plaqueOpen?'':'hidden')+'><small>'+L('A01 · 校园守护者','A01 · Campus guardians')+'</small><h3>'+owners().map(esc).join(' · ')+'</h3><p>'+C.points(s)+' '+L('绿色积分 · 守护预览','green points · Guardian preview')+'</p><p>'+L(C.points(s)<100?'还差 '+(100-C.points(s))+' 分达到演示门槛':'已达到 100 分演示门槛',C.points(s)<100?(100-C.points(s))+' more points to the demo threshold':'100-point demo threshold reached')+'</p></div></div><div class="game-meta"><span>'+L('点树上的小牌，展开守护名字','Tap the small plaque to see your guardians')+'</span><strong>'+C.points(s)+'/100</strong></div><div class="xp-track"><i style="width:'+C.points(s)+'%"></i></div><div class="actions">'+button(L('编辑共养名字','Edit guardian names'),'open-friends','secondary')+button(L('查看用水积分','Water & points'),'open-records')+'</div><details class="details"><summary>'+L('校园相册 · 我们的实拍','Campus album · Our photographs')+'</summary><div class="gallery">'+[['treeA01',L('A01 · 未加牌原始实拍','A01 · Original, no added plaque')],['treeA02',L('A02 · 树木观察','A02 · Campus tree')],['treeA03',L('A03 · 已有友谊树纪念牌','A03 · Existing Friendship Tree')],['aerial',L('校园夜景','Campus at night')],['discussion',L('小组分工讨论','Team task discussion')],['demoReview',L('小组原型讨论','Team prototype discussion')]].filter(([key])=>A[key]).map(([key,label])=>'<figure><img src="'+A[key]+'" alt="'+label+'" loading="lazy"><figcaption>'+label+'</figcaption></figure>').join('')+'</div></details>'+note(L('主图的小木牌为 AI 辅助合成，尚未在现实中挂牌。本页展示认养设想，不形成实际认养关系。树种、位置与活动安排需核实。','The small plaque was added with AI assistance; no physical plaque has been installed. This is a concept preview, not an actual adoption. Tree details and arrangements still need verification.'));
    }
    if(panel==='bag')html='<div class="stats"><div class="stat"><strong>'+s.food+'</strong><small>'+L('份鱼粮','food portions')+'</small></div><div class="stat"><strong>'+Number(s.photoWon+s.waterWon)+'/2</strong><small>'+L('挑战徽章','challenge badges')+'</small></div><div class="stat"><strong>'+C.points(s)+'</strong><small>'+L('示例绿色积分','sample green points')+'</small></div></div><div class="cards">'+[['photoWon','photo',L('校园探索徽章','Campus Explorer')],['waterWon','water',L('水路达人徽章','Water Wayfinder')]].map(([key,ico,label])=>'<article class="item-card"><div class="medal '+(s[key]?'':'locked')+'">'+icon(ico)+'</div><h3>'+label+'</h3><small>'+L(s[key]?'已获得 · 首次通关纪念':'完成对应挑战后解锁',s[key]?'Unlocked on your first clear':'Complete its challenge to unlock')+'</small></article>').join('')+'</div><div class="actions">'+button(L('去校园挑战','Campus challenges'),'open-games')+button(L('回去喂鱼','Feed your fish'),'close','secondary')+'</div>'+note(L('鱼粮、徽章和成长属于游戏奖励。绿色积分只来自示例用水记录。','Food, badges and XP are game rewards. Green points only come from the sample water records.'));
    if(panel==='profile')html='<div class="profile-hero"><img src="'+petAsset()+'" alt=""><div><h3>'+esc(s.keeper)+'</h3><small>'+esc(s.name)+' · Lv. '+C.level(s)+' · '+C.xp(s)+'/100 XP</small><div class="xp-track"><i style="width:'+C.xp(s)+'%"></i></div></div></div>'+menuRow('shirt',L('我的小鱼与装扮','My fish & outfit'),'open-wardrobe')+menuRow('leaf',L('小鱼一家','Fish family'),'open-nursery',s.babyType?L('1 条幼鱼','1 baby'):'Lv. '+C.level(s)+'/3')+menuRow('user',L('给小鱼起名','Name your fish'),'open-name',esc(s.name))+menuRow('water',L('用水记录与积分','Water records & points'),'open-records')+menuRow('group',L('共养伙伴','Pond guardians'),'open-friends',String(owners().length))+menuRow('language',L('中文 / English','English / Chinese'),'language',s.lang==='zh'?'中文':'English')+menuRow(s.muted?'mute':'sound',L('游戏音效','Game sound'),'sound',s.muted?L('关闭','Off'):L('开启','On'))+menuRow('book',L('玩法指南','How to play'),'open-help')+menuRow('reset',L('重置试玩','Reset demo'),'open-reset')+menuRow('book',L('项目与素材说明','Project & credits'),'open-about')+'<div class="team-list"><strong>'+L('秦天 · 组长','Qin Tian · Team Leader')+'</strong><br>'+L('陶嘉成 · 王艺凯 · 宋沛桐 · 江昱辰','Tao Jiacheng · Wang Yikai · Song Peitong · Jiang Yuchen')+'</div>'+note(storageAvailable?L('免注册。进度保存在此浏览器；不同设备独立。','No account needed. Progress is saved in this browser; devices are independent.'):L('此浏览器暂不能保存进度；关闭页面后可能丢失本轮试玩。','This browser cannot save progress; this session may be lost when you close the page.'));
    if(panel==='name')html='<label class="section-label" for="name-input">'+L('小鱼的名字（最多 8 字）','Fish name (up to 8 characters)')+'</label><input id="name-input" class="input" maxlength="8" value="'+esc(s.name)+'"><div class="actions">'+button(L('保存名字','Save name'),'save-name','full')+'</div>';
    if(panel==='reset')html='<p>'+L('关卡、鱼粮、成长、积分和徽章将回到初始状态。','Puzzles, food, XP, points and badges will return to their initial state.')+'</p>'+button(L('重新开始，保留小鱼和名字','Restart, keep my fish and names'),'reset-keep','full')+'<div class="actions">'+button(L('全部恢复初始状态','Reset everything'),'reset-all','danger full')+'</div><div class="actions">'+button(L('先不重置','Cancel'),'close','secondary full')+'</div>'+note(L('校园实拍照片始终保留。全部重置还会清除共养名字、装扮和自定义鱼名。','Campus photos are always retained. A full reset also clears guardian names, outfits and your fish’s name.'));
    if(panel==='help')html='<ol class="help-steps">'+[L('在装扮里选一条喜欢的小鱼，调整体型和衣服。','Choose a fish and personalize its size and outfit.'),L('顶部点「喂食」。每次消耗 1 份鱼粮，获得 20 成长值。','Tap Feed at the top. One food gives your fish 20 XP.'),L('底部点「挑战」，完成校园拼图或接水路，领取鱼粮和徽章。','Open Challenges. Complete a photo or pipe puzzle for food and a badge.'),L('打开用水记录，查看示例曲线并领取 20 绿色积分。','Review the sample water chart and collect 20 green points.'),L('前往校园守护，点开小木牌，查看自己和伙伴的名字。','Open Guardian and tap the plaque to reveal your names.')].map(x=>'<li>'+x+'</li>').join('')+'</ol>'+button(L('知道啦，回鱼塘','Got it, back to pond'),'close','full');
    if(panel==='help')html+='<p>'+L('靠近上下边缘展开工具栏；手机轻点入口，键盘可 Tab 到入口。右上角鱼缸按钮可固定工具栏。小鱼升级后体型增大，Lv. 3 可在小鱼一家里迎接幼鱼。','Hover near the top or bottom to reveal controls. On touchscreens, tap the handles; keyboard users can Tab to them. Pin controls with the top-right tank button. Level up to grow your fish, then visit Fish family at Lv. 3 to welcome a baby.')+'</p>';
    if(panel==='about')html='<div class="legal"><p>'+L('滴水成林是我们的校园绿色科技课堂项目。当前是中期课堂原型，尚未接入趣智校园、数据库或跨设备共养。','Campus Reef is our Green Tech class project. This class prototype is not connected to Quzhi Campus, a database, or multi-device co-care.')+'</p><p>'+L('本轮界面参考 Reefy 的全屏鱼缸、顶部操作区、底部任务导航与弹出面板。界面和水景由我们重新实现，未复制其代码、图标、字体文件或游戏素材。','This interface studies Reefy’s full-screen aquarium, compact top controls, bottom navigation and sheets. Our interface and water scene were independently implemented; no Reefy code, icons, font files or game assets were copied.')+' <a href="https://eren-ozcan.github.io/reefy/" target="_blank" rel="noopener noreferrer">Reefy</a> · <a href="https://github.com/Eren-Ozcan/reefy/blob/master/LICENSE" target="_blank" rel="noopener noreferrer">'+L('原项目许可','Original license')+'</a></p><p>'+L('校园景物照片选自团队提供的实拍。鱼角色为照片经 AI 辅助去背景和虚拟换装后的游戏素材，可能包含重建细节，不能作为新增实拍。树牌主图为校园实拍与虚拟木牌的合成预览。','Campus scenery pictures come from the team’s original photographs. Fish are photo-derived game assets with AI-assisted background removal and outfits, and may include reconstructed details. The tree plaque is a composite preview.')+'</p><p>'+L('棕白鱼：用户提供照片。金鱼：Raul654，CC BY-SA 3.0。蓝色斗鱼：Eric Savage，CC BY-SA 2.0。对应衍生素材沿用原许可。','Clownfish: user-provided photo. Goldfish: Raul654, CC BY-SA 3.0. Blue betta: Eric Savage, CC BY-SA 2.0. Their derived assets retain those licenses.')+'</p><p><a href="https://commons.wikimedia.org/wiki/File:Goldfish.jpg" target="_blank" rel="noopener noreferrer">Goldfish source</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a><br><a href="https://commons.wikimedia.org/wiki/File:Betta_splendens_(blue).jpg" target="_blank" rel="noopener noreferrer">Betta source</a> · <a href="https://creativecommons.org/licenses/by-sa/2.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 2.0</a></p><p>'+L('演示数据不代表真实节水效果；守护预览不代表校方已批准认养或挂牌。','Demo data are not evidence of water savings. Guardian previews do not imply school approval for tree adoption or plaques.')+'</p></div>';
    if(panel==='about')html+=note(L('柠檬倒吊、银色神仙鱼和霓虹灯鱼为本项目原创矢量插画。鱼塘中的演示伙伴鱼为脚本角色；幼鱼属于游戏成长机制。','Yellow tang, Silver angelfish and Neon tetra use original vector illustrations made for this project with coding assistance. Pond companions are scripted demo characters, and baby fish are a game growth mechanic.'));
    if(panel==='reward')html=rewardMarkup();
    body.innerHTML=html;hydrate(body);body.scrollTop=0;
    const plaqueButton=body.querySelector('.plaque-hotspot');if(plaqueButton)plaqueButton.classList.toggle('expanded',plaqueOpen);
    if(panel==='photo'){const ref=body.querySelector('.reference img');const syncRatio=()=>{if(ref.naturalWidth){const ratio=ref.naturalWidth+'/'+ref.naturalHeight;body.querySelector('.photo-board').style.aspectRatio=ratio;ref.style.aspectRatio=ratio;}};ref.addEventListener('load',syncRatio,{once:true});if(ref.complete)syncRatio();}
  }
  let reward=null;
  function rewardMarkup(){if(!reward)return'';return'<div class="reward-content"><div class="reward-star">✦</div><h3>'+L(reward.zh,reward.en)+'</h3><div class="reward-value">'+L(reward.valueZh,reward.valueEn)+'</div><p>'+L(reward.detailZh,reward.detailEn)+'</p>'+button(L(reward.next==='campus'?'去看校园守护牌':'带礼物回鱼塘',reward.next==='campus'?'View guardian plaque':'Back to my fish'),'reward-next','full')+'<small>'+L('奖励已保存 · 同一奖励仅领取一次','Saved in this browser · Each reward is granted once')+'</small></div>';}
  function celebrate(data){reward=data;save();open('reward');sound('win');fireworks();}
  function collect(){if(!C.collect(s))return;save();render();celebrate({zh:'每一点改变，都算数',en:'Every small change counts',valueZh:'+20 绿色积分',valueEn:'+20 green points',detailZh:'示例周日均时长 10 → 8 分钟。去看看树上的守护牌吧。',detailEn:'Sample daily duration: 10 → 8 minutes. Your guardian plaque is ready to preview.',next:'campus'});}
  function feed(){if(feeding)return;if(!C.feed(s)){open('food');return;}feeding=true;reacting=false;render();$('pet').classList.add('is-feeding');sound('feed');speech('咕噜～谢谢你的照顾！','Gulp! Thanks for looking after me.');
    for(let i=0;i<5;i++){const dot=document.createElement('i');dot.className='food-dot';dot.style.left=(49+i*1.1)+'%';dot.style.animationDelay=i*.065+'s';$('fish-world').appendChild(dot);setTimeout(()=>dot.remove(),1600);}
    clearTimeout(floatTimer);$('floating-reward').hidden=true;void $('floating-reward').offsetWidth;$('floating-reward').textContent='+20 XP';$('floating-reward').hidden=false;floatTimer=setTimeout(()=>$('floating-reward').hidden=true,1450);save();
    clearTimeout(feedTimer);feedTimer=setTimeout(()=>{feeding=false;$('pet').classList.remove('is-feeding');render();},1200);
  }
  function changeLanguage(){s.lang=s.lang==='zh'?'en':'zh';gameMessage='';save();render();if(panel)renderPanel();}
  function toggleSound(){s.muted=!s.muted;if(s.muted)stopSound();save();render();if(panel==='profile')renderPanel();}
  function clearTransient(){clearTimeout(feedTimer);clearTimeout(fishTimer);clearTimeout(floatTimer);feeding=false;reacting=false;$('pet').classList.remove('is-feeding');$('fish-speech').hidden=true;$('floating-reward').hidden=true;document.querySelectorAll('.food-dot').forEach(x=>x.remove());stopSound();stopFireworks();}
  function action(act,el){
    if(act.startsWith('open-')){gameMessage='';if(act==='open-water')wet=[];open(act.slice(5),act==='open-wardrobe'?'fish':undefined);return;}
    if(act==='close'){close();return;}
    if(act==='language'){changeLanguage();return;}if(act==='sound'){toggleSound();return;}
    if(act==='wardrobe-tab'){sub=el.dataset.value;renderPanel();return;}
    if(act==='choose-fish'){s.fishType=el.dataset.value;s.petChosen=true;save();render();renderPanel();sound('hello');return;}
    if(act==='size'||act==='wear'){s[act==='size'?'fishSize':'fishWear']=el.dataset.value;save();render();renderPanel();return;}
    if(act==='toggle-companions'){s.companions=!s.companions;save();render();renderPanel();return;}
    if(act==='welcome-baby'){if(C.welcomeBaby(s)){save();close();sound('win');toast('幼鱼加入了你的小鱼塘！','A baby fish has joined your pond!');}return;}
    if(act==='save-friends'){s.keeper=$('keeper-input').value.trim().slice(0,12)||C.fresh().keeper;s.partners=C.normalizePartners($('partners-input').value,s.keeper);save();close();toast('共养名字已保存。','Guardian names saved.');return;}
    if(act==='save-name'){const name=$('name-input').value.trim().slice(0,8);if(!name){$('name-input').focus();return;}s.name=name;save();close();toast('小鱼的新名字记好啦。','Your fish’s new name is saved.');return;}
    if(act==='collect'){collect();return;}
    if(act==='gift'){if(!C.claimFood(s))return;celebrate({zh:'小鱼的补给到啦',en:'A little supply for your fish',valueZh:'+2 份鱼粮',valueEn:'+2 fish food',detailZh:'继续陪它长大吧。小游戏也能获得鱼粮。',detailEn:'Keep your fish growing. Mini-games also earn food.',next:'home'});return;}
    if(act==='reward-next'){if(reward?.next==='campus'){plaqueOpen=false;open('campus');}else close();stopFireworks();return;}
    if(act==='plaque'){plaqueOpen=!plaqueOpen;if(plaqueOpen&&C.points(s)>=100){s.certificate=true;save();render();}renderPanel();return;}
    if(act==='reset-keep'||act==='reset-all'){clearTransient();s=C.reset(s,act==='reset-all');plaqueOpen=false;selectedTile=null;wet=[];gameMessage='';save();close();toast('新一轮试玩开始了。','A fresh round is ready.');return;}
    if(act==='photo-source'){s.photo=el.dataset.value;selectedTile=null;gameMessage='';save();renderPanel();return;}
    if(act==='shuffle'){s.tiles=[1,0,2,3,5,4,8,7,6];s.moves=0;selectedTile=null;gameMessage='';save();renderPanel();return;}
    if(act==='tile'){
      const i=Number(el.dataset.index);if(selectedTile===null){selectedTile=i;renderPanel();return;}if(selectedTile===i){selectedTile=null;renderPanel();return;}
      const solved=C.swap(s,selectedTile,i);selectedTile=null;gameMessage=L('继续对照原图，交换两块照片。','Keep comparing with the reference and swap two tiles.');
      if(solved){const first=C.award(s,'photo');gameMessage=L('拼好了！这关奖励只领取一次。','Complete! This challenge rewards you once.');save();render();if(first){celebrate({zh:'校园拼图完成',en:'Campus puzzle complete',valueZh:'+2 份鱼粮',valueEn:'+2 fish food',detailZh:'获得校园探索徽章。把礼物带回小鱼塘吧！',detailEn:'Campus Explorer badge unlocked. Bring your reward back to the pond!',next:'home'});return;}}
      save();renderPanel();return;
    }
    if(act==='pipe'){const i=Number(el.dataset.index);s.rot[i]=(s.rot[i]+1)%4;wet=[];gameMessage=L('接口调整好了，放水试试。','Pipe rotated. Try the flow.');save();renderPanel();return;}
    if(act==='pipe-hint'){gameMessage=L('试试路线：4 → 5 → 2 → 3 → 6 → 9，再从第9格向下流出。','Try this route: 4 → 5 → 2 → 3 → 6 → 9, then flow down out of tile 9.');renderPanel();return;}
    if(act==='flow'){const result=C.trace(s);wet=result.seen;if(result.ok){const first=C.award(s,'water');gameMessage=L('水流到达终点！本关奖励不重复发放。','Water reached the outlet! Rewards do not repeat.');save();render();if(first){celebrate({zh:'小水路接通啦',en:'The water found its way',valueZh:'+2 份鱼粮',valueEn:'+2 fish food',detailZh:'获得水路达人徽章。回鱼塘喂喂你的伙伴。',detailEn:'Water Wayfinder badge unlocked. Time to feed your companion.',next:'home'});return;}}else gameMessage=L('水停在这里了，检查亮起的最后一格和下一格接口。','The flow stopped. Check the last lit pipe and the next connection.');renderPanel();return;}
  }
  document.addEventListener('click',event=>{
    const btn=event.target.closest('button');if(!btn)return;
    if(btn.id==='play'){s.started=true;save();render();$('care-toggle').focus({preventScroll:true});return;}
    if(btn.id==='controls-toggle'){s.controlsPinned=!s.controlsPinned;save();render();return;}
    if(btn.id==='language'){changeLanguage();return;}if(btn.id==='sound'){toggleSound();return;}
    if(btn.id==='close-sheet'){close();return;}if(btn.id==='feed'){feed();return;}if(btn.id==='collect'){open('records');return;}
    if(btn.id==='pet'){if(!feeding){reacting=true;paintFish();sound('hello');speech('看到你啦，今天也一起玩吧。','There you are! Let’s spend some time together.');}return;}
    if(btn.id==='next-goal'){const next=goal().action;if(next==='feed')feed();else{if(next==='campus')plaqueOpen=false;open(next,next==='wardrobe'?'fish':undefined);}return;}
    if(btn.dataset.tab){if(btn.dataset.tab==='home'){if(panel)close();else{sound('hello');speech('你好呀，我在这里。','Hello! I’m right here.');}}else{gameMessage='';open(btn.dataset.tab);}return;}
    if(btn.dataset.open){if(btn.dataset.open==='campus')plaqueOpen=false;open(btn.dataset.open,btn.dataset.open==='wardrobe'?'wear':undefined);return;}
    if(btn.dataset.act)action(btn.dataset.act,btn);
  });
  $('overlay').addEventListener('click',event=>{if(event.target===$('overlay'))close();});
  document.addEventListener('keydown',event=>{if(!panel)return;if(event.key==='Escape'){event.preventDefault();close();return;}if(event.key==='Tab'){const list=[...$('sheet').querySelectorAll('button:not([disabled]),input,summary,a[href],[tabindex="0"]')].filter(el=>el.getClientRects().length);if(!list.length)return;const first=list[0],last=list.at(-1);if(event.shiftKey&&(document.activeElement===first||!$('sheet').contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  function stopSound(){tones.forEach(o=>{try{o.stop();}catch{}});tones.clear();}
  async function sound(kind){if(s.muted)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext??=new Audio();if(audioContext.state==='suspended')await audioContext.resume();if(s.muted)return;const notes=kind==='win'?[523,659,784,1047]:kind==='feed'?[440,587]:[659,880];notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),time=audioContext.currentTime+i*.12;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(.06,time+.015);g.gain.exponentialRampToValueAtTime(.0001,time+.32);o.connect(g);g.connect(audioContext.destination);tones.add(o);o.onended=()=>{tones.delete(o);o.disconnect();g.disconnect();};o.start(time);o.stop(time+.34);});}catch{/* Audio is optional. */}}
  function stopFireworks(){cancelAnimationFrame(confettiFrame);confettiFrame=0;const c=$('fireworks');c.getContext('2d').clearRect(0,0,c.width,c.height);}
  function fireworks(){stopFireworks();if(reduced.matches)return;const c=$('fireworks'),ctx=c.getContext('2d'),w=innerWidth,h=innerHeight;c.width=w;c.height=h;const colors=['#ffd987','#93efcc','#bae4ff','#ffb8a5'];const ps=Array.from({length:95},(_,i)=>({x:w*(.25+(i%3)*.25),y:h*.52,a:Math.random()*Math.PI*2,s:70+Math.random()*190,color:colors[i%4],delay:(i%3)*.18}));const start=performance.now();function frame(now){const t=(now-start)/1000;ctx.clearRect(0,0,w,h);for(const p of ps){const age=t-p.delay;if(age<0||age>1.7)continue;ctx.globalAlpha=Math.max(0,1-age/1.7);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x+Math.cos(p.a)*p.s*age,p.y+Math.sin(p.a)*p.s*age+60*age*age,2.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(t<2.2)confettiFrame=requestAnimationFrame(frame);else stopFireworks();}confettiFrame=requestAnimationFrame(frame);}
  // Independently drawn game environment. It uses no downloaded Reefy assets.
  const water=$('water'),ctx=water.getContext('2d'),back=document.createElement('canvas'),bg=back.getContext('2d'),front=document.createElement('canvas'),fg=front.getContext('2d');let width=0,height=0,lastDraw=0;
  let seed=72;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  function sizeScene(){width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,2);water.width=back.width=front.width=Math.round(width*dpr);water.height=back.height=front.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);bg.setTransform(dpr,0,0,dpr,0,0);fg.setTransform(dpr,0,0,dpr,0,0);drawBackground();PondScenery.paintStatic(bg,fg,width,height);}
  function drawBackground(){
    const g=bg.createLinearGradient(0,0,0,height);g.addColorStop(0,'#abd4d3');g.addColorStop(.57,'#9dcdd1');g.addColorStop(1,'#96c4c9');bg.fillStyle=g;bg.fillRect(0,0,width,height);
    const glow=bg.createRadialGradient(width*.48,height*.12,0,width*.5,height*.35,width*.62);glow.addColorStop(0,'#c7efea44');glow.addColorStop(.5,'#b4e1e30b');glow.addColorStop(1,'#285b6423');bg.fillStyle=glow;bg.fillRect(0,0,width,height);
    for(let i=0;i<5;i++){const ray=bg.createLinearGradient(0,0,0,height*.60);ray.addColorStop(0,'rgba(222,255,246,'+(.1+i*.02)+')');ray.addColorStop(1,'rgba(233,255,251,0)');bg.fillStyle=ray;bg.beginPath();const x=width*(.37+i*.032);bg.moveTo(x,0);bg.lineTo(x+width*.025,0);bg.lineTo(x+width*.13,height*.62);bg.lineTo(x-width*.028,height*.62);bg.closePath();bg.fill();}
    const sandTop=height*.695;bg.beginPath();bg.moveTo(0,sandTop);bg.quadraticCurveTo(width*.5,sandTop-height*.052,width,sandTop);bg.lineTo(width,height);bg.lineTo(0,height);bg.closePath();const sand=bg.createLinearGradient(0,sandTop,0,height);sand.addColorStop(0,'#eee2bb');sand.addColorStop(.4,'#e9dcb1');sand.addColorStop(1,'#d4ca9f');bg.fillStyle=sand;bg.fill();
    bg.save();bg.clip();seed=72;for(let i=0;i<Math.min(1300,width*1.1);i++){const x=random()*width,y=sandTop-18+random()*(height-sandTop+18);bg.fillStyle=i%3?'#776b3015':'#ffffec29';bg.beginPath();bg.arc(x,y,random()*1.3+.4,0,Math.PI*2);bg.fill();}const vignette=bg.createRadialGradient(width*.5,sandTop,0,width*.5,sandTop,width*.65);vignette.addColorStop(0,'#fffff025');vignette.addColorStop(1,'#696a3022');bg.fillStyle=vignette;bg.fillRect(0,sandTop-30,width,height);bg.restore();
  }
  seed=18;const bubbles=Array.from({length:25},()=>({x:random(),y:random(),r:1.2+random()*3.7,speed:.013+random()*.014}));
  function animate(now){requestAnimationFrame(animate);if(document.hidden||now-lastDraw<32)return;lastDraw=now;const t=reduced.matches?0:now/1000;ctx.clearRect(0,0,width,height);ctx.drawImage(back,0,0,water.width,water.height,0,0,width,height);PondScenery.paintPlants(ctx,width,height,t);ctx.drawImage(front,0,0,water.width,water.height,0,0,width,height);ctx.strokeStyle='#e0fffa33';ctx.lineWidth=1.5;bubbles.forEach(b=>{const y=(1-((b.y+t*b.speed)%1))*height,x=b.x*width+Math.sin(t*.6+b.x*13)*7;ctx.beginPath();ctx.arc(x,y,b.r,0,Math.PI*2);ctx.stroke();});
    const x=feeding?width*.52:width*(.48+Math.sin(t*.105)*.20), y=feeding?height*.40:height*(.39+Math.sin(t*.19)*.105);const half=$('pet').offsetWidth/2+8;const petX=Math.max(half,Math.min(width-half,x)),petY=Math.max(125,Math.min(height*.64,y));$('pet').style.left=petX+'px';$('pet').style.top=petY+'px';PondLife.animate(t,width,height,petX,petY);$('pet-image').style.scale=!feeding&&Math.cos(t*.105)<0?'-1 1':'1 1';
  }
  addEventListener('resize',sizeScene);addEventListener('pagehide',()=>{clearTransient();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTransient();render();}});reduced.addEventListener('change',()=>{if(reduced.matches)stopFireworks();});
  PondControls.init();sizeScene();render();requestAnimationFrame(animate);
})();
